plugin:
  has_options: false

  tools:
    - name: formalibre_pia_tool
      is_displayable_in_workspace: false
      is_displayable_in_desktop: true
      class: book

  admin_tools:
    - name: formalibre_pia_admin_tool
      class: book
